fix for issue about attempted deserialization of multipart form data …
PerlDancer/Dancer2 pull request #1678
Opened 2023-02-24 21:45 UTC by emil-perhinschi

… when a serializer is set

a quick solution for issue 1677

2023-02-26 15:44 UTC, cromedome commented
Hi Emil,

Thanks for reporting the bug and for your PR!

I see what you did, and I think it's a fair approach to the problem, but in running the Dancer2 test suite against your proposed fix, it produces a *lot* of uninitialized warning messages that weren't present before. Could you please run your fix against our test suite and resolve the warnings? I'll take another look once the warnings are handled.

Thanks so much!

2023-02-26 21:18 UTC, emil-perhinschi commented
> in running the Dancer2 test suite against your proposed fix, it produces a _lot_ of uninitialized warning messages that weren't present before.

Hello Chromedome, 

I did run `prove -v` inside the lastest Dancer2 `master` branch and there were no uninitialized warnings. 
sftp://192.168.100.51/home/emilper/personal/Dancer2/prove_verbose.log

I have attached the log.

2023-02-27 10:25 UTC, emil-perhinschi commented
Hello Jason, 

you mean the uninitialized errors in https://ci.appveyor.com/project/xsawyerx/dancer2/builds/46335065 ? 

Can't find the file 00-report-prereqs.t in master ... where can I find/get those tests ? 

thank you,

Emil

2023-02-27 10:48 UTC, emil-perhinschi commented
found them, ran, made the fix, ran `dzil test` again, pushed 

Just in case, there are a few modules that are missing in `cpanfile` and not installed by Dist::Zilla: 
Test::CPAN::Meta
Dancer2::Session::Cookie
Test::NoTabs
which appear to be needed in tests

2023-03-03 10:35 UTC, emil-perhinschi commented
Is there another problem with my fix ? AppVeyor build succeeded .

2023-07-26 02:02 UTC, cromedome approved these changes
I would like to see a test to show that the bug is fixed. Nonetheless, this gets a :+1:  from me.

2023-07-27 09:29 UTC, emil-perhinschi commented
updated the pull request with a test

2023-07-31 01:36 UTC, cromedome commented
@emil-perhinschi Awesome. I ran your test without your fixes applied to verify the bug, and again with them to confirm everything works properly.  This gets a big :+1:  from me. 

@xsawyerx? @yanick? Penny for your thoughts!

2023-07-31 13:41 UTC, yanick commented on lib/Dancer2/Core/Request.pm
> +        && $self->serializer
I think this last condition is not necessary. For one it's taken care of at line 196 right below, and for another I think the logical condition here is "no matter if we have a serializer or not, we don't no nuthing if the content type is `multipart/form-data`. Nuthing, I tell you.

2023-07-31 13:41 UTC, yanick requested changes
I have this one comment I left, but beside that, looks good!

2023-07-31 13:44 UTC, yanick commented on lib/Dancer2/Core/Request.pm
> +    # if a serializer is used (JSON or Mutable) the deserialization of
I think the comment describe the problem the code fixes. But without context I am prone to think it describes what the block does. 

Maybe `# don't attempt to deserialize if the form is 'multipart/form-data'`

2023-07-31 14:54 UTC, emil-perhinschi commented
updated as requested

2023-07-31 14:57 UTC, yanick approved these changes

2023-08-11 00:24 UTC, cromedome commented
This was merged but never closed. Thanks again! :)

2023-08-11 00:24 UTC, closed without merging

2023-08-11 08:23 UTC, emil-perhinschi commented
thank you

will it make into a CPAN release ? else we can continue using github and manual installs, but that's not the optimum solution :)

2023-08-11 12:29 UTC, cromedome commented
It's queued up for the next release, tentatively next week.